### ISSUE TITLE
Ensure widths and margins are on correct wrapper & child

### ISSUE THREAD

**Issue by ArcaneIRE** [ArcaneIRE/odin-landing-page#2]
Width should be on inner element. Incorrect example:
```css
.benefits {
    width: var(--width-percent)-10%;
    max-width: var(--max-content-width);
    margin: 0 auto;
    padding: 3rem;
}

.benefits-wrapper {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 3rem;
}
```
